env:
  global:
  - DEBUG='* -superagent -express:* -mocha:*'
language: node_js
node_js:
- '0.12'
script: npm test
before_install:
- openssl aes-256-cbc -K $encrypted_3ef9ab604ef5_key -iv $encrypted_3ef9ab604ef5_iv
  -in taskcluster-base-test.conf.json.enc -out taskcluster-base-test.conf.json -d
